#COPY ./backend/target/backend-0.0.1-SNAPSHOT.jar NAME-YOUR-FILE-BUILDSPRINGBOOT.jar
#ENTRYPOINT ["java","-jar","/backend-0.0.1-SNAPSHOT.jar"]
#FROM openjdk:15-jdk
#MAINTAINER EstebanBelmonte
#WORKDIR /app
#COPY ./backend/target/backend-0.0.1-SNAPSHOT.jar .
#CMD ["java", "-jar", "backend-0.0.1-SNAPSHOT.jar"]
